/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'M55_HE.Debug+DevKit-E8' 
 * Target:  'Debug+DevKit-E8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"



#endif /* RTE_COMPONENTS_H */
